//! CDS prediction via Prodigal subprocess or pre-computed FASTA.

use std::path::Path;
use std::process::Command;

use crate::types::*;

/// Load pre-computed CDS from a FASTA file (generated by predict_cds.py).
/// Header format: >contig_name_N # start # stop # strand # contig_len=NNN
pub fn load_precomputed_cds(
    cds_fasta: &Path,
    genome_idx: GenomeIdx,
) -> (Vec<Cds>, u32) {
    let mut cds_list = Vec::new();
    let mut protein_idx = 0u32;

    if let Ok(mut reader) = needletail::parse_fastx_file(cds_fasta) {
        while let Some(Ok(record)) = reader.next() {
            // Extract full header from the raw record data
            // all() returns the full record; first line is the header
            let all = record.all();
            let header_end = all.iter().position(|&b| b == b'\n').unwrap_or(all.len());
            let full_header = String::from_utf8_lossy(&all[1..header_end]).to_string(); // skip '>'
            let coord = parse_cds_header(&full_header, genome_idx);
            let cds_id = format!("{}-protein{}", genome_idx, protein_idx);
            cds_list.push(Cds {
                id: cds_id,
                dna_seq: record.seq().to_vec(),
                genome_idx,
                coord,
            });
            protein_idx += 1;
        }
    }

    (cds_list, 0)
}

/// Run Prodigal on a genome FASTA and extract predicted CDSs.
/// Returns (cds_list, invalid_count).
pub fn predict_cds(
    genome_path: &Path,
    genome_idx: GenomeIdx,
    translation_table: u8,
    prodigal_mode: &str,
    training_file: Option<&Path>,
) -> (Vec<Cds>, u32) {
    let mut args = vec![
        "-i".to_string(), genome_path.to_str().unwrap().to_string(),
        "-f".to_string(), "sco".to_string(),
        "-p".to_string(), prodigal_mode.to_string(),
        "-g".to_string(), translation_table.to_string(),
        "-d".to_string(), "/dev/stdout".to_string(),
        "-q".to_string(),
    ];

    // Use training file from schema if available
    if let Some(trn) = training_file {
        args.push("-t".to_string());
        args.push(trn.to_str().unwrap().to_string());
    }

    let output = Command::new("prodigal")
        .args(&args)
        .output()
        .expect("Failed to run prodigal. Is it installed?");

    if !output.status.success() {
        eprintln!("Prodigal failed for {}: {}",
                  genome_path.display(),
                  String::from_utf8_lossy(&output.stderr));
        return (Vec::new(), 0);
    }

    parse_prodigal_output(&output.stdout, genome_idx)
}

/// Parse prodigal FASTA output into CDS list.
fn parse_prodigal_output(data: &[u8], genome_idx: GenomeIdx) -> (Vec<Cds>, u32) {
    let mut cds_list = Vec::new();
    let mut current_id = String::new();
    let mut current_seq = Vec::new();
    let mut protein_idx = 0u32;

    for line in data.split(|&b| b == b'\n') {
        if line.starts_with(b">") {
            if !current_seq.is_empty() {
                let cds_id = format!("{}-protein{}", genome_idx, protein_idx);
                let coord = parse_prodigal_header(&current_id, genome_idx);
                cds_list.push(Cds {
                    id: cds_id,
                    dna_seq: std::mem::take(&mut current_seq),
                    genome_idx,
                    coord,
                });
                protein_idx += 1;
            }
            current_id = String::from_utf8_lossy(line).to_string();
            current_seq.clear();
        } else if !line.is_empty() {
            current_seq.extend_from_slice(line);
        }
    }

    // Last sequence
    if !current_seq.is_empty() {
        let cds_id = format!("{}-protein{}", genome_idx, protein_idx);
        let coord = parse_prodigal_header(&current_id, genome_idx);
        cds_list.push(Cds {
            id: cds_id,
            dna_seq: current_seq,
            genome_idx,
            coord,
        });
    }

    (cds_list, 0)
}

/// Parse header from predict_cds.py output.
/// Format: contig_name_N # start # stop # strand # contig_len=NNN
fn parse_cds_header(header: &str, genome_idx: GenomeIdx) -> Option<CdsCoord> {
    let header = header.trim_start_matches('>');
    let parts: Vec<&str> = header.split(" # ").collect();
    if parts.len() < 4 {
        return None;
    }

    // Extract contig name (everything before _N suffix in first part)
    let first_part = parts[0].trim();
    let contig_id = if let Some(pos) = first_part.rfind('_') {
        first_part[..pos].to_string()
    } else {
        first_part.to_string()
    };

    let start: u32 = parts[1].trim().parse().ok()?;
    let stop: u32 = parts[2].trim().parse().ok()?;
    let strand: i8 = parts[3].trim().parse::<i8>().ok()?;

    // Parse contig_len from key=value pairs
    let mut contig_len = 0u32;
    for part in &parts[4..] {
        for kv in part.split(';') {
            let kv = kv.trim();
            if let Some(val) = kv.strip_prefix("contig_len=") {
                contig_len = val.parse().unwrap_or(0);
            }
        }
    }

    Some(CdsCoord {
        genome_idx,
        contig: contig_id,
        start,
        stop,
        strand,
        contig_len,
    })
}

/// Parse Prodigal FASTA header to extract coordinates.
/// Format: >contig_N # start # stop # strand # ...
fn parse_prodigal_header(header: &str, genome_idx: GenomeIdx) -> Option<CdsCoord> {
    let header = header.trim_start_matches('>');
    let parts: Vec<&str> = header.split(" # ").collect();
    if parts.len() < 4 {
        return None;
    }

    let contig_id = parts[0].trim().to_string();
    let start: u32 = parts[1].trim().parse().ok()?;
    let stop: u32 = parts[2].trim().parse().ok()?;
    let strand: i8 = parts[3].trim().parse::<i8>().ok()?;

    Some(CdsCoord {
        genome_idx,
        contig: contig_id,
        start,
        stop,
        strand,
        contig_len: 0, // filled later from genome FASTA
    })
}

/// Read genome FASTA and get contig lengths.
pub fn get_contig_lengths(genome_path: &Path) -> Vec<(String, u32)> {
    let mut contigs = Vec::new();

    if let Ok(mut reader) = needletail::parse_fastx_file(genome_path) {
        while let Some(Ok(record)) = reader.next() {
            let id = String::from_utf8_lossy(record.id()).to_string();
            let len = record.seq().len() as u32;
            contigs.push((id, len));
        }
    }

    contigs
}
